# Generated by Django 3.0.4 on 2020-05-31 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200531_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 19, 52, 40, 122210, tzinfo=utc), verbose_name='date published'),
        ),
    ]
